framework:
    translator:      { fallback: "%locale%" }

sonata_intl:
    timezone:
          default: America/Argentina/Buenos_Aires

sonata_admin:
    title:      'ProyectoBase'
    #title_logo: '/bundles/sonataadmin/logo_title.png'
    templates:
        layout:    ::standard_layout_sonata.html.twig
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
            # Customize this part to add new block configuration
            #- { position: right, type: sonata.block.service.text, settings: { content: "<h2>Proyecto Base</h2> <p>Symfony 2.3+</p>"} }
            #- { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}

fos_user:
    db_driver:        orm # can be orm or odm
    firewall_name:    main
    user_class:       Application\Sonata\UserBundle\Entity\User

    group:
        group_class:  Application\Sonata\UserBundle\Entity\Group

    registration:
        confirmation:
            enabled:    true

    from_email:
        address:        noreply@proyecto-base.com
        sender_name:    Admin            

sonata_user:
    security_acl:           false
    impersonating_route:    dashboard # or any route you want to use (ex homepage)
    class:
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group

    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata.user.profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.admin_doctrine_orm.block.audit:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

        # Some specific blocks from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~